# Generated by Django 5.2 on 2025-05-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLeftSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(verbose_name=255)),
                ('category', models.CharField(verbose_name=10)),
                ('current_quantity', models.IntegerField()),
                ('min_stock_level', models.IntegerField()),
            ],
            options={
                'db_table': '"warehouse"."product_inventory_view"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(verbose_name=255)),
                ('category', models.CharField(verbose_name=10)),
                ('current_quantity', models.IntegerField()),
            ],
            options={
                'db_table': '"warehouse"."product_inventory_view"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSummaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='product_summary/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
