# Generated by Django 5.2 on 2025-05-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_summaryfile_delete_productsummaryfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
