# Generated by Django 5.2 on 2025-05-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_alter_summaryfile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryfile',
            name='format',
            field=models.CharField(default='csv', max_length=10),
            preserve_default=False,
        ),
    ]
