# Generated by Django 5.2 on 2025-05-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_summaryfile_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementSummary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField()),
                ('operation_date', models.DateTimeField()),
            ],
            options={
                'db_table': '"warehouse"."product_movement_view"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductMovementSummary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('operation_type', models.CharField()),
                ('operation_date', models.DateTimeField()),
                ('quantity_change', models.IntegerField()),
                ('balance_after_operation', models.IntegerField()),
            ],
            options={
                'db_table': '"warehouse"."product_movement_full_view"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRunOutSummary',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(verbose_name=255)),
                ('category', models.CharField(verbose_name=120)),
                ('stock_difference', models.IntegerField()),
            ],
            options={
                'db_table': '"warehouse"."product_availability_view"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ProductLeftSummary',
        ),
        migrations.AlterField(
            model_name='summaryfile',
            name='format',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='summaryfile',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
