# Generated by Django 5.2 on 2025-05-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': '"warehouse"."category"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('operation_id', models.IntegerField()),
                ('quantity_change', models.IntegerField()),
                ('balance_after_operation', models.IntegerField()),
                ('user_id', models.TextField()),
                ('comments', models.TextField()),
            ],
            options={
                'db_table': '"warehouse"."operation"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=255)),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('operation_date', models.DateTimeField()),
                ('user_id', models.TextField()),
                ('comments', models.TextField()),
            ],
            options={
                'db_table': '"warehouse"."operation"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': '"warehouse"."unit_of_measure"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='LogMessage',
        ),
        migrations.AlterModelTable(
            name='product',
            table='"warehouse"."product"',
        ),
    ]
